version: "3.9"
services:
  app:
    build: .
    image: petlands:latest
    restart: unless-stopped
    env_file: .env
    expose:
      - "8000"
  nginx:
    image: nginx:1.25-alpine
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
